config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'main#home'
  post '/time_log/new', to: 'time_log#create'
  delete '/time_log/:id/destroy', to: 'time_log#destroy'
  get '/time_log/:id/edit', to: 'time_log#edit'
  get 'home/dashboard', to: 'main#dashboard'  
  get 'home/stimulus', to: 'main#stimulus'  
  #get 'time_log/:id', to:"time_log#show"
  resources :time_log
 
  resources :users do
    resources :time_logs
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/time_log.rb
class TimeLog < ApplicationRecord
  belongs_to :user
  
  validates :summary, presence: true, length: { maximum: 240 }
  validates :time_spent, presence: true
  validates :log_date, presence: true
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :time_logs
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
      @articles = Article.all
    end
    
  end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end

  def dashboard
  end
end

app/controllers/time_log_controller.rb
class TimeLogController < ApplicationController
    def show
        @timelog = TimeLog.find(params[:id])
    end

    def create
      @timelog = TimeLog.new(timelog_params)
  
      if @timelog.save
        redirect_to @timelog, notice: 'Time log was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @timelog = TimeLog.find(params[:id])
    end
  
    def update
      @timelog = TimeLog.find(params[:id])
    
      if @timelog.update(timelog_params)
        redirect_to @timelog
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @timelog = TimeLog.find(params[:id])
      @timelog.destroy

      redirect_to "/home/dashboard", status: :see_other
    end
  
  
    private
    def timelog_params
      if params[:action] == "create"
        params.permit(:summary, :note, :log_date, :time_spent, :user_id)
      else
        params.require(:time_log).permit(:id, :summary, :note, :log_date, :time_spent, :user_id)
      end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/time_log_helper.rb
module TimeLogHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">HOME</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="http://localhost:3000/home/dashboard">DASHBOARD</a>
        </li>
        
      </ul>
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item" style="padding-top:10px; padding-right:15px"> <%= current_user.email %> </li> 
          

          <div class="dropdown">
          <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown button
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li class="nav-item"> <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %></li>
            <li class="nav-item"> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-small btn-primary mx-2" %></li>
          </ul>
        </div>

        <% else %>
          <li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"> <%= link_to "Sign In", new_user_session_path, class: "nav-link"  %></li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Iana Longo Dandis </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body style="">
  <div style="text-align:">
    <%= render 'layouts/navbar' %>
    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
        <%= flash[:alert] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/main/dashboard.html.erb
<style>
td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}
table {
  margin-left: auto; 
  margin-right: auto;
  overflow-x: auto; 
}
</style>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div style="text-align:center" class="">
  <br>
  <div style="text-align:center; padding-left:40px; color:gray "><h1>DASHBOARD </h1><br>
</div>
<div style="text-align:center">
  <% if current_user %>
 
    <div style="padding-left:40px;">
    <table>
    <thead>
        <tr>
        <th>summary</th>
        <th>time_spent</th>
        <th>log_date</th>
        <th style="width:30%">note</th>
        <th>user_id</th>
        <th>read</th>
        <th>edit</th>
        <th>delete</th>
        </tr>
    </thead>
    <tbody>

    <% timelogs = TimeLog.where(user_id: current_user.id).order(log_date: :desc) %>
    <% timelogs.each do |timelog| %>
        <tr>
        <td><%= timelog.summary %></td>
        <td><%= timelog.time_spent.strftime("%H:%M")  %></td>
        <td><%= timelog.log_date.strftime("%Y-%m-%d") %></td>
        <td><%= timelog.note %></td>
        <td><%= timelog.user_id %></td> 
        <td>
          <a href="/time_log/<%= timelog.id %>">
            read
          </a>
        </td>
        <td>  <a class="" href="http://localhost:3000/time_log/<%= timelog.id %>/edit"> edit </a> </td>
        <td> 
        <% timelogid = timelog.id %>
        <%= link_to "delete", url_for("http://localhost:3000/time_log/#{timelogid}/destroy"), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } %> 
      </td>
        </tr>
        <% end %>
    </tbody>
    </table>
</div>
<br> <br>
<div style="text-align:left; padding-left:40px">
  <a class="btn btn-primary" href="http://localhost:3000/time_log/new"> create new TimeLog </a>
  
  <%= link_to "Crea nuovo TimeLog", new_time_log_path %>
</div>
<br>

  <%else%> 
    <%= image_tag "hello.jpg", height: 400 %>
    <p style="font-size:25px">please <%= link_to "Sign Up", new_user_registration_path %> or 
    <%= link_to "Sign In", new_user_session_path %> <br> for visit your dashboard </p>
  <% end %>

</div>

app/views/main/home.html.erb
<div style="text-align:center" class="">
  <br>
  
</div>
<div style="text-align:center">
  <% if current_user %>
   <p style="font-size:28px"> Hello <b style="color:orange"> <%= current_user.email %> </b></p>
  <% end %>
  <p style="font-size:25px"> Take a look at my latest projects</p>
</div>

<div style="padding-left:15%; padding-right:15%;">

<% Article.all.each do |article| %>

  <div style="border-radius:30px; text-align:left">
    <div style="padding:30px">
     <b style="color:black; text-transform: uppercase;"> <%= article.title %> </b><br>
     <a href="<%= article.link %>"> <%= article.link %> </a>
     <p> <br> <%= article.body %> </p>
    </div>
  </div>
  <hr>
  <% end %>
</div>

app/views/main/stimulus.html.erb
<div data-controller="dropdown">
  
    <p>Qui faccio le mie prove con il stimulus! </p>
  
</div>

app/views/time_log/_form.html.erb
<style>
.form-control{
  text-align:left; 
}
</style>

<%= form_with model: timelog do |form| %>
  <div>
    <%= form.label :summary %><br>
    <%= form.text_field :summary, class:"form-control" %>
  </div>

  <div>
    <%= form.label :note %><br>
    <%= form.text_area :note, class:"form-control" %>
  </div>

  <div>
    <%= form.label :log_date%><br>
    <%= form.text_field :log_date, class:"form-control", value: DateTime.now.strftime("%Y-%m-%d") %>
  </div>

  <div>
    <%= form.label :time_spent%><br>
    <%= form.text_area :time_spent, class:"form-control", value: Time.now.strftime("%H:%M:%S")  %>
  </div>
  
  <div>
    <%= form.label :user_id%><br>
    <%= form.text_field :user_id, class:"form-control", value: current_user.id, readonly: true %>
  </div>

  <div style="text-align:center; padding-top:30px">
  <%= form.submit "Save TimeLog", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/time_log/edit.html.erb
<div class="col-lg-4 col-md-4 col-sm-4 container justify-content-center" style="width:50%; padding-top:50px">
<div style="text-align:center"><h1>Edit Timelog</h1></div>
      <%= render "form", timelog: @timelog %>

</div>

app/views/time_log/new.html.erb
<style>
.form-control{
  text-align:center; 
}
</style>

<div class="col-lg-4 col-md-4 col-sm-4 container justify-content-center" style="width:50%; padding-top:50px">
  <div style="text-align:center"><h1>Create New Timelog</h1></div>
    <%= render "form", timelog: @timelog %>
</div>

app/views/time_log/show.html.erb
<style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: lightgray;
  width:20%;
}
</style>
<div style="padding-top:30px">
<h1>TimeLog </h1><br>

<table id="customers">
  <tr>
    <th>Summary</th>
    <td><%=@timelog.summary %></td>
  </tr>
  <tr>
    <th>Note</th>
    <td><%= @timelog.note %></td>
  </tr>
  <tr>
    <th>Log Date</th>
    <td><%= @timelog.log_date.strftime("%Y-%m-%d") %></td>
  </tr>
  <tr>
    <th>Time spent</th>
    <td><%= @timelog.time_spent.strftime("%H:%M") %></td>
  </tr>
  
</table>
</div>
<br>
<a class="" href="http://localhost:3000/home/dashboard">< back to DASHBOARD</a>